# 跟韌體 inc/command_opcodes.h 對齊。任何一邊改動 opcode 數值，
# 另一邊也要跟著改，這兩個檔案目前是手動同步，沒有自動產生機制。

# Dilithium
CMD_DILITHIUM_SELFTEST = 0x01
CMD_DILITHIUM_REKEY = 0x02
CMD_DILITHIUM_GET_PUBKEY = 0x03
CMD_DILITHIUM_SIGN = 0x04
CMD_DILITHIUM_VERIFY = 0x05

# ML-KEM
CMD_KEM_GET_PUBKEY = 0x10
CMD_KEM_DECAPSULATE = 0x11
CMD_KEM_ENCAPSULATE = 0x12
CMD_KEM_REKEY = 0x13

# AES-GCM
CMD_AES_ENCRYPT = 0x20
CMD_AES_DECRYPT = 0x21

# 共用
CMD_CLEAR = 0xF0
