# 跟韌體 inc/command_opcodes.h 對齊。任何一邊改動 opcode 數值，
# 另一邊也要跟著改，這兩個檔案目前是手動同步，沒有自動產生機制。

# ML-DSA-44（FIPS 204 最終標準；前身是 CRYSTALS-Dilithium round 3，
# 兩者不是同一份規格，命名對齊實際演算法版本）
CMD_MLDSA_SELFTEST = 0x01
CMD_MLDSA_REKEY = 0x02
CMD_MLDSA_GET_PUBKEY = 0x03
CMD_MLDSA_SIGN = 0x04
CMD_MLDSA_VERIFY = 0x05

# ML-KEM
CMD_KEM_GET_PUBKEY = 0x10
CMD_KEM_DECAPSULATE = 0x11
CMD_KEM_ENCAPSULATE = 0x12
CMD_KEM_REKEY = 0x13
CMD_KEM_SET_AUTH_MODE = 0x14
CMD_SET_HOST_MLDSA_PUBKEY = 0x15

# ML-KEM handshake 簽章認證模式（給 CMD_KEM_SET_AUTH_MODE 用）
# 跟韌體 command_opcodes.h 的 KEM_AUTH_* 對齊
KEM_AUTH_NONE = 0x00
KEM_AUTH_DEVICE_SIGNS = 0x01
KEM_AUTH_HOST_SIGNS = 0x02
KEM_AUTH_BOTH = 0x03

# AES-GCM
CMD_AES_ENCRYPT = 0x20
CMD_AES_DECRYPT = 0x21

# 共用
CMD_CLEAR = 0xF0
